/* Pali/English word pairs. Pali is Velthius format, e.g.:  aa, .m, ~n, "n */
/* Additional words from Gair, New Course in Reading Pali (those which are
 * not already in pali2010.js). From chapter 7 onwards not all words from 
 * Dhammapada verses have been added. */

var jwtInputCaption = "Gair";

var jwtInputWords = new Array(

"caption: Lesson 01",
"anuyogo # application, practise",
"antaradhaana.m # disappearance",
"aarambho # attempt, effort",
"kosajja.m # indolence",
"chando # desire, will, resolution",
".thiti # persistence, continuance",
"nivaareti # keeps back",
"pagga.nhaati # holds up",
"padahati # strives, exerts",
"paaripuuri # fulfillment, completion",
"parivaareti # accompanies, surrounds",
"parihaayati # decreases, deteriorates",
"pho.t.tabba.m # touch, contact",
"bhaavanaa # development",
"bhiyyobhaavo # increase, growth",
"samanupassati # perceives",
"sammoso # bewilderment, confusion",
"vaayamati # strives, struggles",
"vepulla.m # fullness, abundance",

"caption: Lesson 02",
"a~n~natra # elsewhere",
"a.nha / aha # day (compound form)",
"upasampadaa # aquiring, undertaking, higher ordination",
"uppaado # arising, birth",
"e.lamuuga # deaf and dumb",
"ottappii # afraid of wrong-doing (adj)",
"kudaacana.m # at any time",
"paccaajaayati # is reborn",
"pa.tibala # able, competent",
"pa.tilaabho # attainment",
"pati.t.thaati # stands firmly, is established",
"pariyodapanaa # purification",
"pubba.nho # forenoon",
"paapa.niko # shopkeeper, merchant",
"phaati # increase",
"bhabba # capable, able",
"sakkacca.m # carefully, thoroughly",
"sanantana # ancient, old, eternal",
"saaya.nho # evening",
"saavajja # blameable, faulty",
"hiri # sense of shame, modesty",

"caption: Lesson 03",
"padiipeti # lights, kindles",
"abhijjaalu # covetous one",
"daaraa # young woman, married woman",
"hita.m # benefit, welfare",
"tathatta.m # that-state",
"samatta.m # eveness, equality",
"samatta # complete, entire",
"paatu # in front, visible, manifest (indecl)",
"bahuliikata # much practised",
"sampayogo # association",
"vippayogo # dissociation",
"icchaa # desire, wish, longing",
"sota.m # ear",
"jivhaa # tongue",
"pho.t.thabba.m # touch, contact",
"kalla # smart, clever",

"caption: Lesson 04",
"(upak)kileso # defilement, impurity",
"upakkili.t.tha # impure, stained",
"tapati (tap) # shines, is bright",
"virocati (vi+ruc) # shines, is brilliant",
"suraa # intoxicant, liquor",
"meraya.m # fermented liquor",
"(pa.ti)virata # abstained",
"(pa.ti)viramati (ram) # abstains",
"methuna.m # sexual intercourse",
"pa.tisevati (sev) # follows, practises, indulges in",
"saadiyati (saad) # enjoys for oneself, agrees, permits",
"ga.nhaati (gah) # takes, grasps, holds",
"pa.tigga.nhaati (pa.ti+gah) # takes, accepts, receives",
"saavikaa # female disciple",
"tasati (tas) # trembles, is frightened, is thirsty, craves for",
"ghaato # killing, destruction, robbery",
"sahita.m # literature, scriptures",
"go # ox, cattle",
"saama~n~na.m # state of a monk, holy life",
"soko # sorrow, grief",
"pema.m # love, affection",
"rati # love, attachment, liking for",
"unnala # arrogant, proud",
"capala # unsteady, fickle",
"mukhara # talkative, noisy",
"(vi)kirati (vi+kir) # scatters (about), spreads (all over)",
"(vi)ki.n.na # scattered (about), strewn (all over)", 
"sampajaana # thoughtful, mindful",
"vibbhamati (vi+bham) # goes astray, wanders about",
"paakata # common, vulgar, uncontrolled",
"vaggo # group, party, chapter",
"vagga # dissociated, dissentious",
"bha.n.dana.m, kalaho # dispute, quarrel ",
"dippati (dip) # shines",
"pamatta # negligent, indolent",
"mata # dead",
"visesato # distinctively, altogether (adv)",
"ramati (ram) # delights in, enjoys oneself",
"(vip)pasiidati (vi+pa+sad) # becomes bright / clear / purified / pleased",
"ghana # solid, compact, massive",
"tanuka # small, thin, little",
"vipassati # sees clearly, has intuition",
"netti # guide, conductor, support",
"usukaaro # fletcher",
"tejana.m # point of an arrow",
"tacchako # carpenter",
"gihii (m) # one who leads domestic life",
"nekkhamma.m # renunciation",
"nirupadhi # free from passion or attachment (adj)",
"aamisa.m # raw meat",
"cakka.m # wheel, circle, cycle",

"caption: Lesson 05",
"rakkhaa # protection",
"upajiivati (upa + jiiv) # lives on, depends on",
"sippa.m # art, craft",
"puthu # spread out, far and wide, individual",
"vohaaro # trade, business, merchandise",
"pessiko # messenger, servant",
"issattha.m # bow, archery",
"yodho # warrior, soldier",
"yaajako # one who sacrifices",
"ra.t.tha.m # reign, kingdom, country",
"yoni # origin, womb",
"ki~ncano # wordly attachment",
"paritassati (tas) # is excited, worried, tormented",
"sa.mgaatigo # gone beyond attachment",
"visa.myutta # detached",
"se.t.thataa # excellence, foremost place",
"pasa.msati # praises",
"sadaa # forever",
"rucira # agreeable, attractive",
"vaacaa # speech",
"kubbati # does, performs",
"jaagarati (jaagar) # is wakeful, watchful",
"sa.msaaro # life cycle ",
"sevanaa # association",
"aarati # abstinence",
"sa.myamo # restraint, self-control",
"baahusacca.m # great learning",
"sikkhati (sikkh) # learns, trains oneself, practises",
"nivaato # humbleness, gentleness",
"kata~n~nutaa # gratitude",
"khanti # patience, forbearance",
"sovacassataa # obedience, gentleness",
"aahuneyya # worthy of offerings",
"paahuneyya # worthy of hospitality",
"dakkhi.neyya # worthy of gifts",
"sata (adj) # mindful, conscious",
"upekkhaa # neutrality, equanimity",
"upekkhaka (adj) # indifferent, disinterested",
"ghaano # nose",
"a~njalikara.niiya # worthy of respectful salutation",
"ajjhatta.m # inwardly, internally",
"sandi.t.thika # visible",
"ajjatagge # from now on",
"digu.na.m # doubly",
"da.n.deti # punishes",
"tatta # heated, hot",
"ayo # iron",
"gu.la.m # sugar, molasses, ball",
"aaditta # burning, ablaze",
"jalati (jal) # shines, burns",
"sampajjalita # ablaze, in flames",
".dayhati (dah) # gets burned",
"vipari.naamo # change",
"vedanaa # feeling, sensation",
"sa~n~naa # perception, recognition, sign",

"caption: Lesson 06",
"sikkhaapada.m # rule, precept",
"verama.nii # abstinence",
"thala.m # land, dry ground",
"ninna # low lying, bent down",
"pecca (ind) # after death",
"vyuu.lha # removed, scattered",
"ja.tilo # one who has matted hair",
"assamo # hermitage",
"uddhana.m # fire place, oven",
"ma.nika.m # big jar",
"svaatana # relating to the morrow",
"anutappati (tap) # regrets, repents",
"taapeti (tap) # scorches, torments, heats",
"nandati (nand) # is glad, rejoices",
"vitakko # reflection, thought",
"(sa.m)vijjati (vid) # is found, exists",
"sikkhaa # study, discipline",
"paccakkhaati (khaa) # rejects, refuses, gives up",
"aavattati (vat) # goes back, turns around",
"tanti # string, cord (of musical instrument)",
"vi.naa # lute",
"aayata # long, stretched",
"sithila # loose, lax",
"gu.no # virtue, quality, string",
"uddhacca.m # distraction, flurry",
"kodhana # peevish, uncontrolled",
"jaani # deprivation, loss",
"nigacchati (gam) # undergoes",
"aayasakya.m # dishonour, disgrace",
"sammatta # intoxicated, much delighted",
"suhajja.m # amity, friendship",
"vajjati # is avoided",
"pakopana # making turbulent, agitating",
"avabujjhati (budh) # understands",
"sahati (sah) # overcomes, endures",
"tamo / tama.m # darkness, ignorance",
"ottappa.m # shrinking back from wrong-doing",
"manasikaaro # consideration",
"yavo # barley, grain",
"laavati # cuts, mows",
"uuhana.m # consideration, lifting up",
"lunaati (lu) # cuts off, mows, reaps",
"vaama # left, agreeable",
"daatta.m # sickle",
"kalaapo # bundle, sheaf",
"kittaavataa # in what respect?",
"sandosa.m # pollution, defilement",
"va.d.dhati (va.d.dh) # grows, prospers",
"manujo # a human being",
"viya # like",
"maaluvaa # parasite creeper",
"palavati # floats, swims",
"soko # grief, sorrow",
"visattikaa # attachment, craving",
"udabindu # drop of water",
"duraccaya # difficult to overcome",

"caption: Lesson 07",
"anussava.m # tradition, hearsay",
"paramparaa # lineage, succession",
"itikira # hearsay (thus-truly)",
"sampadaana.m # handing on, giving over",
"garu # heavy, serious, honored, teacher",
"munaati (mum) # knows, understands",
"santika # near, in the vicinity",
"atipaateti (pat) # kills, fells",
"pakopo # anger, fury, agitation",
"anuyu~njati (yuj) # attends",
"nipaka # clever, intelligent",
"parissaya.m # obstacle",
"attamana # delighted, glad",
"raago # color, lust, attachment",
"ratta # infatuated with lust",
"vidhameti (dham) # destroys, ruins, scatters",
"vida.mseti / vidasseti (dis) # shows, exhibits",
"paaka.ta # well-known, famous",
"guyha.m # secret, what is to be hidden",
"vaso # control, influence, authority",
"bhiiru(ko) # coward",
"so.n.do # drunkard",
"pa.n.dako # weakling, eunuch",
"hetu # cause, reason, condition",
"lola # greedy, unsteady",
"sikataa # sand",
"ittara # short-lived, brief, small",
"calati (cal) # moves, stirrs, trembles",
"cala # moving, unsteady",

"caption: Lesson 08",
"saaveti (su) # causes to hear, tells, declares",
"abbhuta # astonishing, marvellous",
"parisuddha # clear, pure, bright",
"pariyodaata # very clean, pure",
"chavi # skin",
"taala # palmtree",
"urabbho # ram",
"vacchataro # weaned calf, bullock",
"sampati # just now",
"upakkha.ta # prepared, ready",
"thuu.no # pillar, post",
"upaneti # offers, presents",
"aadaana.m # taking up, grasping",
"ussaapeti # raises, lifts up, erects",
"aanisa.mso # profit, merit, good result",
"aavahati (vah) # brings, bears",
"sameti # agrees with, compares",
"damatho # training, taming, restraint",
"medhaa # wisdom",
"lahu # light, lightly",
"aayasmant # venerable one",
"anava.t.thita # unsettled, unsteady",
"pasaado # tranquility, purity, serenity",
"plava # floating",
"payirupaasati # associates",
"dabbii # spoon, ladle",
"suupo  # soup, curry",
"muhutta.m # a moment, a minute",
"assumukha # with a tearful face",
"patiruupa # agreeable",
"niveseti # establishes, arranges",
"kilissati # is stained, does wrong",
"senaa # army",
"daayaka # giver, supporter",
"manaapa # pleasing, charming",
"visaarada # confident, skilled",
"samparaayika # pertaining to the next world",
"kiriyaa # action, deed",
"pavatti # happening, incident",
"pa.nidahati # puts forth, longs for",
"maayaa # deceit, fraud",
"ri~ncati (ric) # neglects, abandons, empties",
"pesuna.m # slander",
"taadisa # of such nature",
"socati (suc) # grieves",
"siigha # quick, rapid, swift",
"kiiva # how much? how long?",
"duura # distant, far",
"ucca # tall, high, lofty",
"niica # low, humble, inferior",
"pa.thamatara.m # as early as possible, first of all (adv)",
"pa.thavii (f)# earth",

"caption: Lesson 09",
"cetiya.m # pagoda, tumulus",
"apadeso # reason, statement",
"manasikaroti # keeps in mind, thinks over",
"sammukha # face to face",
"pa.tikkosati # blames, rejects",
"pada.m # foot, word, place, reason",
"bya~njana.m # syllable, mark",
"otaareti (tar) # causes to descend, brings down",
"sandasseti (dis) # points out, explains",
"sandissati (dis) # is seen, agrees with",
"ni.t.thaa # conclusion",
"addhaa (adv) # certainly",
"phaasu # comfort, ease",
"uccayo # accumulation",
"bhadra # auspicious, good",
"alla # wet, moist",
"namassati # venerates",
"he.t.thima # below",
"uparima # above",
"maaneti # respects, honors",
"sakkaroti (kar) # respects, honors",
"garukaroti (kar) # respects, honors",
"apaayo # woeful state, hell",
"apagacchati (gam) # goes away from",
"vijayo # victory, triumph",
"duddasa # difficult to see",
"duranubodha # difficult to understand",
"takka.m # thought, reasoning, logic",
"avacara # moving in, frequenting",
"nipu.na # efficient, subtle",
"aalayo # desire, attachment",
"pajaa # generation, mankind, offspring",
"samudeti (i) # arises",
"samatho # cessation, calming down",
"pa.tinissago # giving up, rejection",
"viraago # absence of desire",
"khayo # destruction",
"kilamatho # fatigue, weariness",
"vihesaa # vexation, annoyance",
"sekho # learner",
"phe.na.m # foam, froth",
"vindati (vid) # enjoys, knows, realizes",
"baalya.m # childhood, folly",
"maanii # one who is proud",

"caption: Lesson 10",
"ga.no # crowd, gang",
"sodheti (sudh) # causes to become clean",
"so.n.daa # elephant trunk",
"gha.to / gha.ta.m # pot",
"pa.t.thahati (.thaa) # puts down, sets down",
"divaso # day",
"u.nha # warm, hot",
"gha.mseti (gha.ms) # rubs against",
"pakkhipati (khip) # throws, puts",
"khuddaka # small",
"naanaavidha # various",
"vaa.lo # beast of prey",
"aru.no # dawn",
"sa.n.do # heap, cluster, multitude",
"so.n.dii # a natural tank in the rock",
"nipphatti # result, effect, accomplishment",
"pii.tha.m # seat, chair, stool",
"sappati (sapp) # crawls, creeps",
"va.to # banyan tree",
"he.t.thaa # below, down, underneath",
"sakkharaa # gravel, grain",
"aadini # and so forth",
"palaayati (pal) # runs away, escapes",
"chidda.m # hole, defect",
"pharati (phar) # pervades, fills",
"atimukhara # very talkative",
"upaddavati # annoys, troubles",
"la.n.dikaa # animal dung",
"saa.ni # curtain",
"kattari # scissors",
"bhāvo (mostly in cpmds) # condition, nature, becoming",
"lapati (lap) # speaks, talks",
"nissayati (sa) # leans on, relies on",
"vu.t.thi # rain",
"attan # self",
"viha~n~nati (han) # suffers",
"visuddhi # purity",
"tappati (tap) # suffers, is tormented",
"su/duggati # good/bad state",
"upa.t.thaana.m # attendance",
"madhu # honey",
"ko.ti # summit, end",
"a.n.daka.m # egg",
"sanika.m # slowly",
"apaneti (ni) # removes, leads away",
"khaa.nu # spike",
"matthako # head, top, summit",
"nibbijjhati (vidh) # pierces, breaks through",
"gatta.m # body",
"nibbattati (vat) # is born, arises",
"vejjo # physician",
"bhesajja.m # medicine",
"saami # lord, sir, master",
"pakati # original/natural form",
"dhiitar # daughter",
"vidahati (dhaa) # arranges, commands",
"va~nceti (va~nc) # cheats",
"kiidisa # in what manner?",
"rujati (ruj) # pains, aches",
"chaata # hungry",
"sambahula # many",
"tikicchati # cures, treats medically",
"aahaaro # food, nutriment",
"bila.m # hole, den, portion",
"nipajjati (pad) # lies down, sleeps",
"da.lha # firm, strong",
"giivaa # neck",
"nivarati (var) # screams, shouts",
"aviduura # near",
"ko.t.thaaso # share",
"kaara.na.m # reason, cause",
"upaayo # method, trick",
"susira # perforated, having a hole",
"yutta # proper",
"a.t.ta.m # lawsuit",
"pacchindati (chid) # puts an end",
"vinicchinaati (chi) # investigates, decides, tries",
"palaala.m # straw",
"olambati (lab) # hangs down, rests on",
"addho # a half",
"jhaama # burnt, charred",

"caption: Lesson 11",
"nibaddha.m # always",
"sineha.m # affection, love",
"vaaro # turn, occasion, opportunity",
"pakkhandati (khand) # springs forward, jumps on",
"bhussati (bhus) # barks",
"velaa # time",
"sallakkheti (lakkh) # observes, considers",
"viima.msati # tests, considers",
"tiriya.m # across",
"vaareti (var) # hinders, obstructs, prevents",
"nivattati (vat) # turns back",
"payaati (yaa) # goes forward, proceeds",
"nivaasana.m # undergarment, dress",
"ka.n.na.m # ear, angle, corner",
"aparabhaaga # later",
"jiirati # destroys, gets old",
"phaasuka # pleasant, convenient",
"bahi # external, outside",
"vehaaso # sky",
"phalati (phal) # bears fruit, splits",
"hadaya.m # heart",
"tiracchaano # animal, beast",
"ku.tila # crooked, dishonest",
"bhavana.m # abode, residence",
"gaathaa # stanza",
"vitta.m # property, wealth",
"ci.n.na # travelled over, resorted to, performed",
"saadu # sweet, pleasant",
"padeso # region, place, location",
"jagati # earth, world",
"pasahati (sah) # oppresses, subdues",
"ji.n.na # became old, decayed",
"rogo # disease, illness",
"ni.d.dham # nest, place",
"pabhaa # light, radiance",
"puuti # rotten, putrid, stinking",
"deho # body",
"bhogga # bent",
"paraayana.m # final end, support, rest",
"pavedhati (vadh) # trembles, agitates",
"aatura # sick, diseased, miserable",
"yobbana.m # youth",
"kha.n.da # broken",
"keso # hair of head",
"palita # matured, greyed",
"khalita # bald",
"valita # wrinkled",
"tilako # spot, stain, freckle",
"aahanati (han) # beats, strikes, touches",
"jaraa # decay, old age",
"mahallaka # old",
"baa.lha # strong, much, excessive",
"gilaana # sick, unwell",
"mutta.m # urine",
"kariisa.m # dung, excrement",
"palipanna # fallen or sunken into",
"niila # blue",
"vipubbaka # full of corruption, festering",
"pa.tipadaa # way, method, path",
"avecca # absolutely, certainly",
"pasaado # clearness, brightness, joy, faith",
"pharusa # rough, harsh, unkind",
"sampha.m # useless talk, frivolity",
"palaapo # nonsense",
"patho # path, way, road (in cmpds)",
"alasa # idle, lazy",
"dakkha # clever, able, skilled",
"aave.nika # special, separate",
"paccanubhoti (bhuu) # undergoes, experiences",
"dahara # young in years",
"vinaa # without",
"gabbho # interior, womb",
"vijaayati (jan) # gives birth",
"poso # man",
"suura # valiant, courageous",
"disampati (m) # king",

"caption: Lesson 12a",
"aahuti # oblation, offering",
"mu.n.da # shaven, bare",
"vasalo # out-cast",
"saadhu # well, thoroughly",
"upanaahi (adj) # one who bears ill-will, finding fault",
"vipajjati (pad) # fails, goes wrong, perishes",
"dayaa # sympathy, compassion, kindness",
"rundhati (rudh) # obstructs, besieges, imprisons",
"sam~n~naata # designated",
"pahuu # able",
"bharati (bhar) # bears, supports",
"bhaatar # brother",
"roseti (rus) # irritates, annoys",
"kadariya # miserly, stingy",
"sa.tha # fraudulent",
"nikkujjeti (kuj) # turns upside down",
"ukkujjeti (kuj) # turns up",
"aacikkhati (cikkh) # tells, informs",
"dakkhati (dis) # sees",
"pakaaseti (kas) # makes known, illustrates",
"avajaanaati (~naa) # despises",
"sa.mvaaso # association, intimacy",
"abhi.nha # continuous, habitual",
"ukkaa # torch, meteor, forge of smith",
"apacita # honored, esteemed",
"panta # distant, secluded",
"sayana.m # bed",
"paatimokkho # collection of rules in the Vinaya",
"nibbidaa # disgust with wordly life, indifference",
"nimitta.m # sign, omen, cause",
"subha # pleasant, good",
"upasa.mhita # connected with",
"ujjahati (ha) # gives up",
"anusayo # proclivity",
"abhisamayo # realization, comprehension",
"anuvaata # with the wind",
"pa.tivaata # against the wind",
"mala.m # impurity, stain, dirt",
"macchara.m # avarice, niggardliness",
"asuka # such and such",
"pavaati (vaa) # blows forth",
"pilandhana.m # ornament",
"ko.t.teti (ku.t.t) # pounds, beats",
"ma.t.ta # smoothed, polished",
"ku.n.dala.m # earring",
"pa.n.du # yellowish",
"taco # bark, hide, skin",
"kicca.m # duty, work",
"saapateyya.m # wealth, property",
"aalindo # veranda",
"devasika # daily",
"aa.laahana.m # cremation ground"

);
