/* Pali/English word pairs. Pali is Velthius format, e.g.:  aa, .m, ~n, "n */
/* Miscellaneous stuff (e.g., derivative suffixes, numbers, prefixes). */

var jwtInputCaption = "Misc";

var jwtInputWords = new Array(

"caption: Derivatives",
	"noun / adj. + -ika # nom. deriv. suffix: pertaining to, engaged in, possessing",
	"noun / adj. + -ima # nom. deriv. suffix:  pertaining to, possessing",
	"noun / adj. + -iya # nom. deriv. suffix:  pertaining to, comparitive",
	"noun + -(v)ii / -vant / -mant # nom. deriv. suffix: possessing",
	"noun + -maya # nom. deriv. suffix: made of",
	"noun / adj. + -taa / -tta / -ya # nom. deriv. suffix: collection, state, quality",
	"adj. + -tara (+ abl. / + gen.) # nom. deriv. suffix: comparitive / superlative",
	"adj. + -tama / -i.t.tha # nom. deriv. suffix: superlative",
	"numeral + -ka # nom. deriv. suffix: group of certain size",
	"numeral + -kkhattu.m # nom. deriv. suffix: number of times",
	"noun / adj. + -dhaa / -thaa / -so # nom. deriv. suffix: distributive adverb",
	"verbal root + -a # verbal deriv. suffix: masc. abstract noun",
	"verbal root + -aka / -ta# verbal deriv. suffix: agent of action",
	"verbal root + -ana # verbal deriv. suffix: neuter abstract noun / in the habit of, disposed to",
	"verbal root + -ti # verbal deriv. suffix: fem. abstract noun",
	"verbal root + -ii # verbal deriv. suffix: in the habit of, disposed to",
	"infinitive + -kaama # verbal deriv. suffix: desirous of",

"caption: Numbers",
	"eka # one",
	"dvi # two",
	"ti # three",
	"catu # four",
	"pa~nca # five",
	"cha # six",
	"satta # seven",
	"a.t.tha # eight",
	"nava # nine",
	"dasa # ten",
	"ekaadasa # eleven",
	"dvaadasa, baarasa # twelve",
	"terasa, te.lasa # thirteen",
	"cuddasa, catuddasa # fourteen",
	"pa~ncadasa, pa.n.narasa # fifteen",
	"so.lasa, sorasa # sixteen",
	"sattadasa, sattaarasa # seventeen",
	"a.t.thadasa, a.t.thaarasa # eighteen",
	"ekuunaviisati # nineteen",
	"viisati # twenty",
	"ti.msati, ti.msaa # thirty",
	"cattaa.liisati, cattaa.liisaa # fourty",
	"pa.n.naasa, pa~n~naasaa # fifty",
	"sa.t.thi # sixty",
	"sattati # seventy",
	"asiiti # eighty",
	"navuti # ninety",
	"sata.m # hundred",
	"sahassa.m # thousand",
	"lakkha.m # hundred thousand",
	"ko.ti # ten million",
	"pa.thama # first",
	"dutiya # second",
	"tatiya # third",
	"catuttha # forth",
	"pa~ncama # fifth",
	"cha.t.tha # sixth",
	"sattama # seventh",
	"eko - ekaa - eka.m # one (nom.)",
	"dve, duve # two (nom.)",
	"tayo - tisso - tiini # three (nom.)",
	"cattaaro - catasso - cattaari # four (nom.)",
	
"caption: Prefixes",
	"aa- # prefix: as far as, around, reversing to",
	"abhi- # prefix: towards, over, special",
	"adhi- # prefix: upon, over, great, excessive",
	"anu- # prefix: following, after, subordinate",
	"apa- # prefix: away from",
	"api- # prefix: over, near to, on",
	"ati- # prefix: beyond, excessive",
	"ava-, o- # prefix: down, away",
	"du(r)- # prefix: bad, difficult",
	"ni- # prefix: down, away, without",
	"nii- # prefix: away, without",
	"pa- # prefix: towards, forward, forth",
	"paraa- # prefix: away from",
	"pari- # prefix: around, about, completely",
	"pa.ti- # prefix: back, opposite",
	"sa.m- # prefix: together",
	"su- # prefix: good, well",
	"u(d)- # prefix: up, out of, away from",
	"upa- # prefix: towards, subordinate",
	"vi- # prefix: apart, separate"

);
