/* Pali/English word pairs. Pali is Velthius format, e.g.:  aa, .m, ~n, "n */
/* All words from the Pali Programme 2010 in Dhammagiri which are a mix of:
 *  - all Pali Primer lessons
 *  - Warder, Intro to Pali, lessons 01 - 17
 *  - Gair, New Course in Reading Pali, lessons 01 - 06 in parts */

var jwtInputCaption = "Pali2010";

var jwtInputWords = new Array(

"caption: Causatives",
" aamantaapeti (mant) # causes to be addressed, invites ",
" aarocaapeti (ruc) # causes to be informed ",
" aaropeti (ruh) # causes to mount, shows, disproves ",
" bhaaveti (bhuu) # causes to be, develops ",
" chedaapeti (chid) # causes to cut ",
" janeti (jan) # causes to be born, produces ",
" jhaapeti (jhaa) # causes to burn, sets fire ",
" kaareti, kaaraapeti (kar) # causes to work / make / build, governs ",
" kappaapeti (kapp) # causes to be arranged ",
" mu~ncaapeti (muc) # causes to be free, sets free ",
" nibbaapeti (vaa) # causes to be extinct, extinguishes ",
" nipaateti (pat) # causes to fall down, drops ",
" nisiidaapeti (sid) # causes to sit down ",
" paateti (pat)#causes to fall, fells",
" paayeti (pa) # causes to drink ",
" pabbaajeti (vaj) # causes to go forth, banishes ",
" pa.tiyaadaapeti (yad) # causes to be prepared ",
" pavatteti (vat) # causes to go, sets going, keeps on ",
" pavedeti (vid) # causes to be known ",
" paveseti (vis) # causes to enter, brings in ",
" parisodheti (sudh) # causes to become pure ",
" ropaapeti (ruh) # causes to plant ",
" ropeti (ruh) # causes to grow, plants ",
" saaveti (su) # causes to hear ",
" samaadapeti (sa.m+aa+daa)#incites, instigates",
" .thapeti, .thaapayati (.thaa) # causes to stand, erects, keeps, places ",
" vaaceti (vac) # causes to speak, recites ",
" vaadeti (vad) # causes to say, plays instrument",
" yaapeti (yaa) # causes to go, keeps going ",
" yojaapeti (yuj) # causes to be yoked ",

"caption: Nouns",
" aabaadho # disease, illness ",
" aabhaa # shine, luster, sheen ",
" aacariyo # teacher ",
" aajivo # livelihood ",
" aakaaso # sky, space ",
" aaloko # light ",
" aama (indec) # yes ",
" aapa.na.m # market ",
" aapas # water ",
" aaraamo # garden, grove, monastic grounds",
" aasana.m # seat ",
" aasavo # influx, influence ",
" aavaa.to # pit ",
" aavasatho # room, cell ",
" aavuso (vocative ind.) # sir, brother, friend ",
" aayaamo # length ",
" aayu.m # long life, vitality, age ",
" .thaana.m # place, condition, cause ",
" a.tavi (f) # forest ",
" a.t.thi (n) # bone ",
" a.mga.m / a\"nga.m # component, member ",
" a\"nguli (f) # finger, toe ",
" abbhokaasa # open, free, outside, open air ",
" abhijjhaa # covetousness ",
" abhikkanta.m # excellent, superb, wonderful ",
" acchariyo # wonderful, marvelous ",
" adhara # lower",
" adhipati (m) # lord, master, ruler ",
" agaara.m # house, dwelling place ",
" aggi (m) # fire ",
" aggo # top, foremost ",
" aha.m (pron) # I ",
" ahi (m) # snake, serpent ",
" ajja (indec) # to-day ",
" ajo # goat ",
" akusala # bad, unwholesome ",
" amacco # minister ",
" amanusso # non-human being ",
" ambho # sir! (not very respectful) ",
" amu (pron) # that",
" aavila # agitated, stirred up; dirty ",
" anagaariya.m # homelessness ",
" ananta # infinite ",
" antaraa (indec) # within, between, meanwhile ",
" anattho # misfortune ",
" andha # blind, foolish ",
" a~n~na (pron) # other ",
" anna.m # food ",
" a~n~natara, a~n~natama (pron) # a certain ",
" antarena (indec) # between (w/ genitive) ",
" anto # side, end, extreme ",
" anuttara # unsurpassed, supreme ",
" appa.tivattiya # not to be rolled back ",
" appa(ka)  # small, little ",
" ara~n~na.m # forest ",
" ari (m) # enemy ",
" asani (f) # thunderbolt ",
" asappuriso # no-good man ",
" asi (m) # sword ",
" asso # horse ",
" atiita # past ",
" atha (indec) # then, now, also ",
" atha kho (indec) # moreover, rather, then ",
" atikkamo # the passing beyond",
" atithi (m) # guest ",
" ato (indec) # from here, hence, therefore ",
" atra (adv) # here ",
" attho # meaning, welfare ",
" avijjaa # ignorance ",
" ayoniso (indec) # unmethodically, improperly ",
" baalo # fool, child ",
" biija.m # seed ",
" bahu(ka) # much, plenty ",
" bahuvacana.m # plural ",
" bala.m # strength, power, force ",
" bandhana.m # bond, fetter ",
" bhaago # share, portion ",
" bhaajana.m # vessel, itensil ",
" bhaaro # weight, burden, load ",
" bhaasita.m # saying ",
" bhuupalo # king ",
" bhuupati (m.) # king ",
" bhuutapubba.m # formely ",
" bhagavant # fortunate one (Buddha) ",
" bhaagineyyo # nephew ",
" bhaginii # sister ",
" bha.n.da.m # goods ",
" bha.ne # I say! ",
" bha.n.dikaa # parcel, bundle ",
" bhatta.m # boiled rice, meal ",
" bhava.m # good fortune ",
" bhavo # existence, state ",
" bhaya.m # fear, danger ",
" bhedo # splitting up, disunion, division ",
" bhi\"nkaro # ceremonial vessel ",
" bhikkhu # monk ",
" bhogo # possession, wealth ",
" bhojana.m # meal, food ",
" braahama.nii # brahmin woman ",
" braahmano # priest, brahmin ",
" brahman # the brahma, the creator ",
" bubbu.lo # bubble ",
" buddho # buddha ",
" byaapaado # ill-will ",
" caago # giving up, generosity ",
" ciivara.m # robe ",
" ca (indec) # and ",
" cakkavattii # universal monarch ",
" cakkhu.m # eye ",
" candimas # moon ",
" ce (conditional particle) # if ",
" cando # moon ",
" cetas # mind, heart ",
" cira.m (indec) # for (or after) long time ",
" citta.m # mind ",
" coro # thief ",
" daana.m # donation, charity ",
" daani (indec) # now ",
" daarako # boy ",
" daaru.m # wood ",
" daasavya.m # slavery ",
" daaso # slave ",
" daa.thii (m) # tusker",
" diipi (m) # panther ",
" diipo # light, island ",
" duuto # messenger ",
" daddu (f) # eczema, cutaneous eruption ",
" dakkhi.na # southern, right (hand) ",
" danta.m # tooth ",
" da.n.do # stick, punishment ",
" dassana.m # insight, witness, seeing ",
" deso # point (topic) ",
" devii # goddess, queen ",
" devataa # deity, divinity ",
" devo # deity, king ",
" dhaatu (f) # element ",
" dhammo # nature, doctrine ",
" dhana.m # wealth ",
" dha~n~na.m # corn, grain ",
" dhenu (f) # cow, female animal ",
" dhuva # fixed, stable ",
" di.t.thaa (indec) # Wonderful! ",
" disaa # direction ",
" do.ni (f) # boat, canoe ",
" doso # anger ",
" duccarita.m # bad conduct ",
" dukkha.m # suffering ",
" dussa.m # cloth ",
" dvaara.m # door ",
" dvidhaa (indec) # twofold, twice, in two ",
" ekacca  # someone, some, certain, a few ",
" eka.msena (indec) # certainly ",
" ekavacana.m # singular ",
" ekato (indec) # on one side, together ",
" eko # one, some ",
" eta (pron) # this ",
" etarahi (adv) # now, at present ",
" ettha (adv) # here, in this case ",
" eva / 'va / yeva (ind) # emphatic particle: only, just, surely, etc ",
" eva.m (ind) # thus ",
" gaamapada.m # site of a village ",
" gaamo # village ",
" gaaravo # respect ",
" gaavii # cow ",
" giita.m # sound ",
" gahapati (m) # householder ",
" gambhiira # deep, profound ",
" gandho # smell, odour ",
" geho / geha.m # house ",
" ghara.m # house ",
" ghoso # noise, sound ",
" giri (m) # mountain ",
" gocaro # sphere, range, pasture ",
" go.no # ox ",
" gotta.m # clan ",
" guutho # dung ",
" haa # alas! ",
" ha # indeed ",
" haritaka # green, fresh ",
" hattho # hand ",
" hatthii (m), karii (m) # elephant",
" hi # indeed ",
" hira~n~na.m # gold ",
" hura.m (indec) # in the other world ",
" iddha # powerful ",
" iddhi # prosperity, potency, psychic power ",
" idha, iha (adv) # here ",
" ima (pron) # this",
" imaani (pro) # these ",
" indriya.m # faculty, sense ",
" isi (m) # sage ",
" issaro # lord, master ",
" itara (pron) # other ",
" ito (indec) # from here, from now ",
" itthii # woman, female ",
" ittha.m (adv) # in this way ",
" itthi # woman, female ",
" jaataruupa.m # gold ",
" jaati (f) # birth ",
" jiivita.m # life ",
" jiivo # life-principal, soul ",
" jala.m # water ",
" -janana.m / -janano # causing, bringing, producing ",
" janapado # country ",
" jayo # victory ",
" jhaana.m # meditation ",
" ka (pron) # what?",
" kaako # crow ",
" kaalo # time ",
" kaamo # love, passion, like, pleasure ",
" kaarako # doer ",
" kaasu (f) # pit ",
" kaayo # body ",
" kaayo # body ",
" ka.t.tha.m # wood, firewood ",
" ka\"nkhaa # doubt ",
" kacci (indec) # perhaps? did? I hope? I doubt if? ",
" kadalii # plantain tree, banner ",
" kadaa # when? at which time?",
" kakaco # saw ",
" kalyaa.na # beautiful ",
" kamaniiya # lovely ",
" kammaaro # smith ",
" kamma.m # action, deed ",
" kamma~n~na # fit for work, ready for playing ",
" ka.n.tho # throat ",
" ka.neru (f) # she-elephant ",
" kapi (m) # monkey ",
" kassako # farmer ",
" kasmaa # from what (reason)? why?",
" katama, katara (pron) # which, what (of many) ",
" katha.m  # how ",
" ka.t.tha.m # firewood ",
" kavi (m) # poet ",
" khaadaniya.m # hard solid foods, dishes ",
" khiira.m # milk ",
" khiirodakiibhuuta # like milk & water ",
" kha\"nkhaa # doubt ",
" khaggo # sword ",
" khandho # group, collection, mass ",
" khattiyo # warrior, noble ",
" khema # safe, secure ",
" khetta.m # field ",
" khippa.m (ind) # quickly ",
" khoma.m # flax ",
" kiccha.m # difficulty ",
" kodho # anger, ill will ",
" kucchi (m) # belly ",
" kuddaalo # spade, hoe ",
" kuhi.m, kattha, kutra # where?",
" kukkuro # dog ",
" kumaarii # girl ",
" kumaaro # boy ",
" kusiita (adj) # lazy ",
" kusala (adj) # good, wholesome ",
" kusala.m # good deed, wholesome action ",
" kusuma.m # flower ",
" kuto # whence? where (place) from? ",
" kuto pana # let alone, much less ",
" ku.t.thii (m) # leper",
" laabho # gain, profit ",
" lobho # greed ",
" locana.m # eye ",
" loko # world ",
" luddako # hunter ",
" maa.navo # young brahmin ",
" maatulo # uncle ",
" muula.m  # root, money ",
" muula.m # root ",
" maccharin # selfish ",
" maccho # fish ",
" macco # man ",
" maccu (f) # death ",
" madaniiya # intoxicating ",
" maggo # path, road ",
" mahanta # great ",
" mahaamatto # chief minister ",
" mahaaraajan # great king ",
" majjhima (adj) # middle ",
" makkato # monkey ",
" manas # mind, heart ",
" ma~nco # bed ",
" mantii (m) # minister",
" manto # prayer, hymn, charm ",
" manusso # human being, man ",
" manusso # human being ",
" ma.ni (m) # jewel, gem ",
" mariici # mirage ",
" mara.na.m # death ",
" mattaa # measure; quantity; moderation ",
" megho # rain, cloud ",
" miccha (indec) # wrongly, false ",
" migo # deer, animal ",
" mitto # friend ",
" moho # dellusion, ignorance ",
" mu.t.thi (m) # fist, handle ",
" muddhaja (adj) # lingual ",
" muni (m) # sage ",
" musaa (adv) # falsely ",
" mutto # one who is freed ",
" naa.li (f) # measure capacity, tube ",
" naago # elephant, snake ",
" naama (indec) # by name ",
" ~naa.na.m # knowledge ",
" naarii # woman ",
" naaviko # sailor ",
" na (indec) # not ",
" nadii (f) # river ",
" nagara.m # city, town ",
" nakho # fingernail, toenail ",
" nanu # isn't it so that ",
" naro # man ",
" nava # new ",
" nayana.m # eye ",
" nibbaana.m # liberation, extinction ",
" nicca # permanent ",
" nidaana.m # source, cause, origin ",
" nidhi (m) # hidden treasure ",
" nindaa # blame, fault ",
" niraamisa # free from sensual desires ",
" nirodho # cessation ",
" nivaaso # abode, resting place ",
" no  # not (emphatic form of na) ",
" nu # ? (reinforcing interrogative particle) ",
" o.t.tho # lip ",
" odano / odana.m # rice ",
" okaaso, avakaaso # opportunity, space, possibility",
" opamma.m # simile, example ",
" paado / paada.m # foot ",
" paaniiya.m # drinking water ",
" paana.m # drink ",
" paa.ni (m) # hand, palm ",
" paa.nii (m) # living being (endowed with breath)",
" paa.no # breath, life ",
" paapa.m # bad, evil ",
" paasaado # palace ",
" paasaa.no # rock, stone ",
" pabbato # mountain ",
" paccantajo # borderer, foreigner ",
" paccantima # bordering, foreign ",
" paccatthika # opponent, opposing ",
" paccayo # cause, means ",
" pacchima # last, western ",
" padiipeyya.m # lightable ",
" padiipo # lamp ",
" padoso # anger ",
" paduma.m # flower, lotus ",
" pahaana.m # abandoning, avoidance ",
" pahuuta # much, abundant ",
" pakkhii (m) # bird",
" palaala.m # straw ",
" pamaado # negligence ",
" pana (indec) # but, however ",
" pa~nho # question ",
" pa.niita # excellent, delicious, delightful ",
" pa.n.na.m # leaf ",
" para, apara (pron) # (an)other ",
" paribbaajako # wanderer ",
" parisaa # assembly ",
" pariyaayo # course ",
" pasa.msaa # praise ",
" passena # on its side ",
" passo # side ",
" pati (m) # husband, master, owner ",
" patto # bowl ",
" pe (peyyaala) # and so on, etc ",
" phiita # prosperous ",
" phala.m # fruit ",
" phasso # contact, touch ",
" pi # also, but, however ",
" pi.t.thito (indec) # behind (w/ genitive) ",
" pi.tako # basket ",
" pi.n.do # alms ",
" pisu.na # malicious ",
" piya # dear ",
" pokkhara.m # lotus leaf ",
" pokkhara.nii # pond, artificial pool ",
" posako # rearer, breeder ",
" pubba (pron) # before, former ",
" pu~njo # heap, pile, mass ",
" pu~n~na.m # merit ",
" puppha.m # flower ",
" puraa.na # old ",
" purato # before, in front of (w/ genitive) ",
" puratthima # eastern ",
" puriso # man, male ",
" purohito # high priest ",
" putto # son ",
" raajan # king ",
" raajaputto # prince ",
" raajinii # queen ",
" raasi (m) # heap, quantity ",
" ruupa.m # form, object, matter ",
" ruupa.m # matter ",
" rahado # lake ",
" rahogata # being alone / in private ",
" rajako # washerman ",
" rajaniiya # exciting ",
" rajas # dust ",
" rajata.m # silver ",
" rajju (f) # rope, cord ",
" rasmi (f) # cord, rein, ray of light ",
" raso # taste ",
" ratana.m # gem, precious thing ",
" ratho # chariot ",
" ratti # night ",
" ravi (m) # sun ",
" rukkhamuula.m # foot of the tree ",
" rukkho # tree ",
" saa (pron) # she ",
" saa.tako # garment, cloth ",
" saamisa # having greed or sensual desire ",
" saamii (m) # lord, husband",
" saa.na.m # hemp ",
" saarathii (m) # charioteer ",
" saasana.m # teaching ",
" saavako # disciple ",
" siiho # lion ",
" siila.m # virtue, precept ",
" siisa.m # head, lead (metal) ",
" suukaro # pig ",
" sa.mvaro # restraint ",
" sa\"nkhadhamo # conch shell blower  ",
" sa\"nkho # conch shell ",
" sabba (adj, pron) # all, every, entire ",
" sabbaso (ind) # completely ",
" sacca.m # truth ",
" sacca.m (indec) # It is true (?) ",
" sace (indec) # if ",
" saddho # faith ",
" saddo # sound, noise ",
" saggo # heaven ",
" sahaayako # friend ",
" sahaayo # friend ",
" sajjhaayo # learning, study ",
" sajjhu.m # silver ",
" saka # own, his/her own ",
" saka.to # cart ",
" sakkaa (indec) # (it is) possible (+inf) ",
" sakunto # bird ",
" saku.no # bird ",
" sama # even, equal, harmonious ",
" samagga # being in unity ",
" samannaagata (adj) # endowed with ",
" sama.no # ascetic, recluse ",
" samayo # time, occasion ",
" sammaa (indec) # rightly, properly ",
" samma (vocative) # my dear! (familiar address) ",
" sammajjani (f) # broom ",
" samudayo # rise, origin",
" samuddo # sea, ocean ",
" sappo # snake ",
" sappuriso # good man ",
" sariira.m # the body  ",
" sara.na.m # refuge ",
" saras # lake ",
" saro # vowel, arrow ",
" sassuu, sassu (f) # mother-in-law ",
" satthavaaho # caravan-merchant ",
" sattho # caravan ",
" satto # being ",
" satto # creature, living being ",
" sava.na.m # ear, hearing ",
" selo # rock ",
" senaasana.m # abode, resting place ",
" se.t.thii (m) # moneylender",
" seyyaa # bed ",
" sigaalo # jackal ",
" sikhii (m) # peacock",
" siras # head ",
" sithila # loose, lax, yielding ",
" so (pron) # he ",
" so.no # dog ",
" sopaano # stairs ",
" sotas # stream ",
" subhaasita (adj) # well-spoken ",
" sucarita # good conduct ",
" sucarita.m # good conduct ",
" sugato # well-gone (Buddha) ",
" sukha.m # happiness ",
" sukhii (m) # one who is happy",
" sukkha- # dry ",
" suko / suvo # parrot ",
" sunakho # dog ",
" suriyo # sun ",
" suro # god, deity ",
" sutta.m # thread ",
" suva.n.na.m # gold, beautiful ",
" taalu (m) # palate ",
" taapaso # hermit ",
" taaraa # star ",
" ta.m (adv) # then, so, now ",
" ta (pron) # he, she, it, that ",
" tadaa (indec) # then ",
" tahi.m, tattha, tatra # there",
" tapas # asceticism ",
" taru.nii # young woman, maiden ",
" tasmaa, tato # therefore, from that ",
" tathaa # thus, in that way ",
" tathaagato # thus-gone ",
" tejas # radiance, splendor, fire ",
" tela.m # oil (sesame oil) ",
" tena (idiomatic) # by that \"way\" ",
" tena hi (idiomatic) # now, if so, in that case ",
" thuupo # pagoda, monument ",
" tikkhatu.m (indec) # thrice ",
" ti.na.m # grass ",
" tu.n.da.m # beak ",
" tu.nhii (indec) # silent, silently ",
" ubha, ubhaya (pron) # both ",
" udaahu (indec) # or ",
" udadhi (m) # ocean ",
" udaka.m # water ",
" uddha.m (indec) # above ",
" ummatta- # mad ",
" upaasako # lay devotee ",
" upadhi (m) # substratum of re-birth; attachment ",
" upamaa # simile, analogy, example ",
" upasamo # calmness, allaying, pacification ",
" uttaana # shallow, superficial, evident, stretch out, lying down ",
" uttama # superior, best, highest ",
" uttaraasa\"ngo # cloak ",
" uttara # northern, upper, more than ",
" uyyaana.m # park ",
" vaa (indec) # or ",
" vaado # debate ",
" vaanaro # monkey ",
" vaanijo # merchant ",
" vaapii # tank, reservoir ",
" vaato # wind ",
" viihi (m) # paddy ",
" vii.naa # lute ",
" visa.m # poison ",
" va.d.dhakii (m) # carpenter",
" vadhuu, vadhu (f) # daugther-in-law ",
" vadho # harm, killing, destruction ",
" vana.m # wood, forest ",
" va.n.no # colour, beauty ",
" va.no # wound",
" vappa.tisaaro # regret ",
" varaaho # pig ",
" vassa.m # rain, rainy season, year ",
" vasundharaa # earth ",
" vattha.m # cloth, garment ",
" vayas # age ",
" veceta- # daft ",
" vedayita.m # sensation, experience ",
" vera.m # enmity, hatred ",
" vetana.m # wage, payment ",
" vi.t.thaaro # breath, detail ",
" vibhatti (f) # case ",
" viggaho # quarrel, strife ",
" vihaaro # abode, monastery ",
" vijjaa # science, knowledge ",
" vijju (f) # lightning ",
" vilepana.m # ointment, cosmetic ",
" vimalo # clear, clean, bright ",
" vinayo # discipline ",
" vi~n~naana.m # consciousness ",
" vi~n~nuu (adj / noun) # wise / wise man ",
" vipaako # result ",
" viriya.m # effort, exertion ",
" visama # unequal, disharmonious ",
" vivaado # dispute, quarrel ",
" vivaaho, aavaaho # marriage, wedding ",
" vivicca # having become isolated ",
" vyaadhi (m) # sickness, disease ",
" vyatta # intelligent ",
" ya (pron) # who, what ",
" yaacako # beggar ",
" yaagu (f) # rice-gruel ",
" yaava (indec) # up to, as far as ",
" ya.t.thi (f) # pole, walking stick ",
" yadaa # when ",
" yadi (indec) # whether ",
" yagghe! (indec) # hear! ",
" yahi.m, yattha, yatra # in which place, where",
" ya.m (indec) # since, if, that ",
" yan nuuna # what now if? what if? ",
" ya~n~no # sacrifice (ritual) ",
" yasas (n. stem in -s) # fame, repute ",
" yasmaa, yato # because, since ",
" yathaa (indec) # just as, in which way ",
" yo (nom. yam) # who ",
" yogaavacaaro # earnest student, one in endeavor exercise ",
" yojana.m # league ",
" yoniso (indec) # methodically, consequentely ",
" yuvati (f) # maiden ",

"caption: Participles",
" aabhata # brought",
" aama.t.tha # touched ",
" aapanna # entered upon, possessing",
" aaropita # disapproved, put on ",
" abbhuggata # disseminated",
" adhigata  # attained, obtained ",
" aaraddha # begun ",
" aasitta # sprinkled ",
" bhinna #  divided, split",
" baddha # bound ",
" bhutta # eaten ",
" chinna #  cut off",
" cuta # died ",
" danta  # tamed ",
" da.t.tha # bitten ",
" dhota # washed ",
" dinna #  given",
" di.t.tha # seen, found ",
" du.t.tha # wicked ",
" gahita # grasped ",
" garahita  # despised ",
" gata # gone ",
" gutta # guarded ",
" hata # killed ",
" ha.ta # taken, carried ",
" hiina #  diminished; low, base, inferior",
" jaata # born",
" kanta # agreeable, lovely, gone ",
" kata # done ",
" ka.t.tha # ploughed ",
" khii.na #  exhausted, wasted",
" khitta # thrown ",
" kilanta # tired ",
" kupita # angered ",
" kuddha # gotten angry ",
" laddha # gained ",
" luddha # was greedy, covetous ",
" mita # measured ",
" muu.lha, sammuu.lha # confused",
" niggahita # refuted, condemned, restrained ",
" nimmita # created ",
" niruddha # stopped, ceased ",
" nisinna # seated",
" ni.t.thita # completed, finished, ready ",
" paccupa.t.thita # is present ",
" parivuta # followed by, surrounded by ",
" pahiina # given up, abandoned ",
" pakka # cooked, matured ",
" pakkanta # gone away, left",
" pa~n~natta # declared, prepared ",
" pasa.t.tha # praised ",
" (vip)pasanna # pleased, purified, bright, clear ",
" pa.tipanna # engaged in, practising ",
" pa.tisalliina # secluded, retired, gone in solitude ",
" patta # reached ",
" pavi.t.tha # entered ",
" phu.t.tha # touched ",
" piita # drunken ",
" pu.t.tha # asked ",
" rakkhita # protected ",
" sa.mvuta # restrained ",
" samaahita # collected, composed ",
" sampanna # succeeded, prospered, happened, endowed with ",
" sannaddha # tied up",
" santa # calmed, pure, tired, exhausted ",
" santu.t.tha # contented, satisfied ",
" .thita # stood ",
" uddhata # unbalanced, disturbed ",
" upapanna # transmigrated, reborn ",
" uppanna # arisen ",
" vivitta # separated, isolated ",
" vimutta # freed ",
" viva.ta # opened ",
" vutta # said, sown ",
" vuttha # lived ",

"caption: Verbs",
"aabharati#brings, carries ",
"aadadaati (aa+daa)#takes ",
"aadiyati (aa+daa)#takes up, grasps ",
"adhi.t.thahati, adhi.t.thaati (adhi+.thaa)#stands on, fixes attention on",
"aagacchati (aa+gam)#comes ",
"aaharati (aa+har)#brings",
"aajaanaati, a~n~naati (aa+~naa) # learns, grasps",
"aaka.d.dhati (aa+ka.d.dh)#pulls, drags",
"aaka\"nkhati (aa+kakh)#wishes for, desires",
"aako.teti (aa+ku.t)#knocks, beats down",
"aamanteti  (aa+mant)#addresses",
"aamasati (aa+mas)#touches, strokes",
"aaneti (aa+ni)#brings",
"aapajjati (aa+pad)#gets into, aquires, produces",
"aarabhati (aa+rabh)#starts, begins",
"aaraadheti (aa+raadh)#satisfies",
"aaroceti (aa+ruc)#informs",
"aaruhati (aa+ruh)#ascends, climbs",
"aasi~ncati (aa+sic)#sprinkles",
"aayaati (aa+yaa)#comes, approaches",
"atirocati (ati+ruc)#outshines, excels",
".dasati (.da.ms)#bites",
"abbhuggacchati (abhi+gam)#rises up, difuses",
"abhijaanaati (abhi+~naa) # knows, discovers",
"abhikkamati (abhi+kam)#goes forward, advances",
"adhigacchati (adhi+ga.m)#attains, acquires",
"akkhaati (aa+kkhaa)#tells, reports",
"akkosati (aa+kus)#scolds",
"anupakkhandati (anu+pa+kkhand)#goes over to, is converted to, joins",
"anussarati (anu+(s)sar)#recollects",
"anusaasati (anu+saas)#instructs",
"anveti # follows",
"apakkamati (a+pa+kam)#goes off",
"apavadati (apa+vad)#disparages",
"apeti (pa+i)#goes way, disappears",
"arahati (arah)#deserves, is worth",
"assasati (aa+ssas)#breathes in",
"avekkhati (va+ikkh)#looks at, consider",
"bandhati (bandh)#ties, binds",
"bhaasati (bhaas)#speaks, says, shines",
"bhaayati (bhi)#is afraid, fears",
"bhajati (bhaj)#associates with",
"bha.nati (bha.n)#says, speaks",
"bha~njati (bha~nj)#breaks",
"bhavati (bhuu)#becomes",
"bhindati (bhid)#breaks, splits",
"bhu~njati (bhuj)#eats, enjoys",
"carati (car)#roams around, conducts",
"cavati (cu)#dies",
"chaadeti (chad)#covers",
"cha.d.deti (cha.d.d)#throws away, rejects",
"chindati (chid)#cuts",
"cinaati (ci)#collects, piles up",
"cinteti (cin)#thinks",
"coreti (cur)#steals",
"dadaati (daa)#gives",
"damayati (dama)#restrains, controls",
"deseti (dis)#teaches, preaches",
"deti (daa)#gives",
"dhaavati (dhaav)#runs",
"dhovati (dhov)#washes",
"dippati (dip)#shines",
"dissati (dis)#is seen, appears, seems",
"eti (i)#goes,  comes",
"gaayati (ge)#sings",
"gacchati (gam)#goes",
"ga.neti (ga.n)#counts, reckons",
"gavesati (gaves)#looks for, searches for",
"ghaayati (ghaa+ya)#smells",
"hanati (han)#kills",
"hanati, hanti (han)#kills, strikes",
"ha~n~nati (han)#is killed, is destroyed",
"harati (har)#carries, takes",
"hasati (has)#laughs",
"haayati (haa)#diminishes",
"hoti (huu)#is, there is",
"icchati (is)#wishes",
"jaaleti (jal)#kindles",
"jaanaati (~naa)#knows",
"jiivati (jiiv)#lives",
"jaayati (jan)#is born",
"jeti / jayati / jinaati (ji)#wins, conquers",
"jhaayati (jhe)#meditates",
"kii.lati (kii.l)#plays",
"kariiyati (kar)#is done",
"karoti (kar)#makes, builds, does",
"kasati (kas)#ploughs",
"katheti (kath)#says, relates",
"khaadati (khaad)#eats, chews",
"khamati (kha.m)#it pleases, it suits, it approves",
"kha.nati (khan)#digs",
"khiiyati (khii)#is exausted, becomes dejected",
"khipati (khip)#throws out, casts",
"kilamati (kila.m)#becomes tired",
"ki.naati (ki)#buys",
"labhati (labh)#gets, obtains",
"maareti (mar)#kills",
"makkheti (makkh)#smears",
"ma~n~nati (man)#imagines, thinks",
"maapeti (maa)#builds, creates",
"manteti (mant)#discusses, consults",
"mi.naati (mi)#measures",
"miiyati (mar)#dies",
"mu~ncati (muc)#releases",
"naaseti (nas)#destroys, ruins",
"naccati (nat)#dances",
"nahaayati (nhaa)#bathes",
"namati (nam)#bends, bows down",
"namayati#bends, fashions",
"neti (ni)#leads, takes away",
"niiharati (ni+har)#takes out",
"nikkhamati (ni+kam)#departs, leaves, goes out",
"nikkhipati (ni+khip)#lays aside",
"nimanteti (ni+mant)#invites",
"nisiidati (siid)#seats",
"obhaaseti (ava+bhaas)#illuminates",
"ocinaati (ava+ci)#picks, plucks",
"oloketi (ava+lok)#looks at",
"oruhati (ava+ruh)#descends",
"otarati (ava+tar)#descends",
"ovadati (ava+vad)#advices",
"paaleti (paal+e)#rules, protects",
"paapu.naati (pa+ap)#reaches, obtains",
"peseti (pe)#sends",
"pii.leti (pii.l)#oppresses, crushes",
"puujeti (puuj)#honours, offers",
"puureti (puur)#fills",
"pa.tisandahati (dah)#reunites, is connected",
"pa.tissu.naati (pat+su)#responds, assents",
"pa.tiyaadeti (pa.ti+yat)#prepares, arranges",
"pabbajati (pa+vaj)#goes forth, renounces",
"pacati (pac)#cooks",
"paggharati (ppa+gghar)#trickes, drips",
"pahiiyati (pa+haa)#is given up, is abandoned",
"paharati (pa+har)#hits, strikes",
"pahoti (pa+huu)#can (emphatic)",
"pajaanaati (pa+~naa) # understands",
"pajahati (pa+haa)#gives up, renounces",
"pakkamati (kam)#goes away",
"pakkosati (pa+kus)#calls",
"pamodati (pa+mud)#rejoices; enjoys; is glad",
"pamuccati (pa+muc)#is delivered, is freed",
"pa~n~naayati (pa+~na)#is understood",
"pappoti (pa+ap)#reaches, obtains",
"paribhavati (pari+bhuu)#despises",
"parivajjeti (pari+vaj)#avoids",
"pariyaadiyati (pari+aa+daa)#uses up, exhausts",
"pariyesati (pari+es)#explores",
"pasavati (pa+su)#generates, flows, acumulates",
"passati (dis)#sees",
"passati (pass)#sees",
"patati (pat)#falls",
"pa.ticchaadeti (pa.ti+chad)#cover over, conceals",
"pa.tijaanaati (pa.ti+~naa) # consents, aggrees",
"pattharati (pa+thar)#spreads, extends",
"pattheti (pa+atth)#aspires, desires",
"pavassati (ppa+vass)#rains heavily",
"pavattati (pa+vat)#moves on, proceeds",
"pavisati (pa+vis)#enters",
"pekkhati (pa+ikkh)#looks on, watches",
"phaaleti (phaal)#splits, breaks",
"phusati (phus)#touches",
"pibati, pivati (paa)#drinks",
"pivati (paa)#drinks",
"pucchati (pucch)#asks",
"rakkhati (rakkh)#protects",
"rodati, rudati (rud)#laments, cries, weeps",
"saayati (saa)#tastes",
"sa.mharati (sa.m+har)#collects",
"sa.mkamati (sa.m+kam)#transmigrates",
"sa.mvattati (vat)#leads to",
"sa.mvibhajati (sa.m+vi+bhaj)#shares",
"sakkoti (sak)#can, is able",
"samiirati (sa.m+iir)#moves, blows",
"sami~njati (sa.m+i~nj)#moves, wavers",
"sa.mjaanaati (sa.m+~naa) # experiences, perceives",
"sammajati (sa.m+majj)#sweeps",
"sammati#ceases, is appeased",
"sammodati (sa.m+mud)#rejoices, delights, exchanges friendly greetings",
"sampajjati (sa.m+pad)#succeeds",
"sannayhati (sa.m+nah)#fastens, ties up",
"sayati (si)#sleeps",
"sibbati (siv)#stiches, sews",
"sobhati (subh)#makes it clear",
"su.naati (su)#listens, hears",
"tajjeti (tajj)#frightens, threatens",
"tanoti (tan)#spreads, expands, stretches",
"thaketi (thak)#shuts, closes",
"ti.t.thati (sthaa) # stays, stands",
"ubbahati (ud+vah)#carries off",
"u.t.thahati (u+.thaa)#stands up",
"u.d.deti (u+.dii)#flies",
"udeti  (u+i)#rises, comes out",
"ugga.nhaati (u(d)+gah)#learns",
"uggharati (ud+gghar)#oozes",
"upa.laaseti (upa+.las)#makes sound",
"upasa.mkamati (ka.m)#approaches",
"upasampajjati (upa+sa.m+pad)#steps into, undertakes, attains, becomes fully ordained",
"upeti (i)#goes to, approaches",
"uppajjati (u+pad)#is born, arises",
"ussahati (u+sah)#tries",
"vadati (vad)#speaks",
"vandati (vand)#salutes",
"vapati (vap)#sows",
"ve.theti (ve.th)#wraps",
"vibhajati (vi+bhaj)#divides",
"viharati (vi+har)#dwells, lives",
"vihe.theti (vi+he.th)#harasses",
"vihi.msati (vi+his)#harms, hurts",
"vijjhati (vidh)#shoots, pierces",
"vijaanaati (vi+~naa) # is conscious, discerns",
"vikki.naati (vi+ki) #sells",
"visajjeti (vi+sajj)#spends",
"vivarati (vi+var)#opens",
"vuccati (vac)#is called, is said",
"vyaakaroti (vi+aa+kar)#explains",
"yaacati (yaac)#begs",
"yaati (yaa)#goes"



);
